export const STRINGS = {
  appName: 'Sunshine App Dashboard',
  enableSMSService: 'Enable SMS Service',
  smsNotPass: 'SMS Not Pass',
  smsNotProcess: 'SMS Not Process',
  smsReceived: 'SMS Received:',
  dataProcess: 'Data Process',
  depositSMS: 'Deposit SMS',
  deliverySMS: 'Delivery SMS',
  invalidSMS: 'Invalid SMS',
  totalSMS: 'Total SMS',
  pending: 'Pending',
  process: 'Process',
  invalid: 'Invalid',
  totalProcess: 'Total Process',
  checkSMSMemory: 'Check SMS Memory',
  smsReport: 'SMS Report',
  wifiConnected: 'You are connected to WiFi',
  licenceVerified: 'Licence Verified',
  licenceNotVerified: 'Licence Not Verified',
  notConnected: 'No Internet Connection',
};